CREATE USER 'bookingroger'@'%' IDENTIFIED WITH mysql_native_password AS 'bookingpassword';
GRANT USAGE ON *.* TO 'bookingroger'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS `bookingroger`;GRANT ALL PRIVILEGES ON `bookingroger`.* TO 'bookingroger'@'%';
